### ISSUE TITLE
Login endpoints fail in Heroku

### ISSUE THREAD

**Issue by 8masterofpuppets8** [GraffiTab/GraffiTab-Backend#25]
The `externalproviders/login` and `api/login` endpoints fail with a `NullPointerException` when tested in Heroku. Seem to work fine locally. 

Here's the stack trace for a call to the endpoint with valid external provider details or login details:

```
2016-04-01T09:51:15.608405+00:00 app[web.1]: java.lang.NullPointerException
2016-04-01T09:51:15.608410+00:00 app[web.1]: 	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
2016-04-01T09:51:15.608411+00:00 app[web.1]: 	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
2016-04-01T09:51:15.608412+00:00 app[web.1]: 	at com.graffitab.server.service.TransactionUtils.executeInTransaction(TransactionUtils.java:38)
2016-04-01T09:51:15.608413+00:00 app[web.1]: 	at com.graffitab.server.service.user.UserSessionService$$FastClassBySpringCGLIB$$a1639cc2.invoke(<generated>)
2016-04-01T09:51:15.608414+00:00 app[web.1]: 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
2016-04-01T09:51:15.608415+00:00 app[web.1]: 	at com.graffitab.server.service.user.UserSessionService$$EnhancerBySpringCGLIB$$1ea5b674.saveOrUpdateSessionData(<generated>)
2016-04-01T09:51:15.608416+00:00 app[web.1]: 	at com.graffitab.server.api.authentication.JsonLoginSuccessHandler.onAuthenticationSuccess(JsonLoginSuccessHandler.java:42)
2016-04-01T09:51:15.608418+00:00 app[web.1]: 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.successfulAuthentication(AbstractAuthenticationProcessingFilter.java:331)
2016-04-01T09:51:15.608419+00:00 app[web.1]: 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:245)
2016-04-01T09:51:15.608420+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
2016-04-01T09:51:15.608421+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-04-01T09:51:15.608422+00:00 app[web.1]: 	at com.graffitab.server.api.authentication.SessionInvalidationFilter.doFilter(SessionInvalidationFilter.java:85)
2016-04-01T09:51:15.608423+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-04-01T09:51:15.608424+00:00 app[web.1]: 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
2016-04-01T09:51:15.608425+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
2016-04-01T09:51:15.608425+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-04-01T09:51:15.608426+00:00 app[web.1]: 	at com.graffitab.server.api.authentication.ClearThreadLocalsFilter.doFilter(ClearThreadLocalsFilter.java:29)
2016-04-01T09:51:15.608427+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
2016-04-01T09:51:15.608427+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-04-01T09:51:15.608428+00:00 app[web.1]: 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
2016-04-01T09:51:15.608429+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2016-04-01T09:51:15.608430+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-04-01T09:51:15.608432+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
2016-04-01T09:51:15.608433+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
2016-04-01T09:51:15.608434+00:00 app[web.1]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
2016-04-01T09:51:15.608435+00:00 app[web.1]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
2016-04-01T09:51:15.608435+00:00 app[web.1]: 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
2016-04-01T09:51:15.608441+00:00 app[web.1]: 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
2016-04-01T09:51:15.608442+00:00 app[web.1]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
2016-04-01T09:51:15.608442+00:00 app[web.1]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
2016-04-01T09:51:15.608450+00:00 app[web.1]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
2016-04-01T09:51:15.608451+00:00 app[web.1]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
2016-04-01T09:51:15.608451+00:00 app[web.1]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
2016-04-01T09:51:15.608452+00:00 app[web.1]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
2016-04-01T09:51:15.608453+00:00 app[web.1]: 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
2016-04-01T09:51:15.608453+00:00 app[web.1]: 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
2016-04-01T09:51:15.608454+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-04-01T09:51:15.608454+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-04-01T09:51:15.608455+00:00 app[web.1]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2016-04-01T09:51:15.608456+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dfernandezm** [comment]
Cannot recreate at the moment.

**Comment by 8masterofpuppets8** [comment]
Tested the endpoints and they seem to work fine now. Not quite sure what was wrong the last few times but now both `/login` and `/externalproviders/login` work nicely.
